### ISSUE TITLE
Unable to check grammar and spelling

### ISSUE THREAD

**Issue by ssahamath** [sylvainhalle/textidote#105]
I have just installed textidote in macOS as jar file. From terminal when I am running the example.tex file as "java -jar textidote.jar --output html example.tex > report.html", the produced report.html does not show any grammar/spelling error but there is definitely some.

**Comment by hassec** [comment]
I think you are missing the `--check en` option for that.

So maybe try `java -jar textidote.jar --check en --output html example.tex > report.html`

Or if your text isn't in English use one of the other supported languages by substituting `en` for the corresponding abbreviation.

**Comment by martisak** [comment]
I have the same problem. It seems to be working on the example.tex file, but not on my own file. 

My file contains a single chapter of .tex-code and starts with `\section{...}`.  If I use `--type md`(`tex` is no different from not specifying the type) I can see that it detects the spelling-mistakes but also complains on all the LaTeX code.

I then used [`latexexpand`](http://mirrors.ctan.org/support/latexpand/latexpand) to create a single file from all chapters. It then seems as if it works ... 

If I wrap my chapter in `\begin{document}`and ´\end{document}`, `textidote` shows grammar and spelling errors again!

**Comment by sylvainhalle** [comment]
Is your problem solved then? Can I close this issue?

**Comment by ssahamath** [comment]
@hassec Thanks for the suggestion. This works now.
@martisak Thanks, yes the check works if wrap everything within \begin{document} and \end{document. 
@sylvainhalle The problem is resolved.

Thanks everyone for your help.
