### ISSUE TITLE
.9 gives a warning about space before the period

### ISSUE THREAD

**Issue by neil-lindquist** [sylvainhalle/textidote#108]
I ran textidote v0.8.1 (the jar on the release page) on a document and it gave me the following warning:
```
* L110C126-L110C134 There should not be a space before the period at the end
  of a sentence. [sh:d:003]
   performance at about \SI{.9}{\%} of peak, and the
```
I changed the `.9` to `0.9` and the warning went away.
I don't know if the fact that I wrap the number in a `\SI` causes a regex to break, or if it always gives a false positive.

**Comment by sylvainhalle** [comment]
Caused by this line: https://github.com/sylvainhalle/textidote/blob/294a8e4ea64290a1c862816865c637d5f3d0ed16/Source/Core/src/ca/uqac/lif/textidote/rules/regex-detex.csv#L5

Always gives a false positive in its current form.
