### ISSUE TITLE
language model not working

### ISSUE THREAD

**Issue by MatisPatel** [sylvainhalle/textidote#114]
Installed using deb package.
Downloaded languagemodel from site and put the en folder in home. 

run command
```
textidote --read-all --remove-macros citep --output html --check en_UK --languagemodel ~/ Chapter06.tex > spellchecks/discussion_check.html
```
get error
> Could not load codec 'Lucene410'.  Did you forget to add lucene-backward-codecs.jar? N-gram rules will be ignored.

**Comment by sylvainhalle** [comment]
Duplicate of #104
