### ISSUE TITLE
Support \subfile in addition to \include

### ISSUE THREAD

**Issue by shankari** [sylvainhalle/textidote#115]
First, thank you for writing this very cool tool. It is super helpful to me as I proofread my thesis. However, I noticed one inconsistency while running the command.

The documentation says:

> TeXtidote also automatically follows sub-files that are embedded from a main document using \input{filename} and \include{filename} (braces are mandatory). Any such non-commented instruction will add the corresponding filename to the running queue.

My thesis uses \subfile for individual chapter sections. This is mainly because the template I use has \subfile instead of \include.

It looks like \subfiles are not added to the queue by default. If I change `\subfile` to `\include`, I get many more corrections.

If it makes sense to add \subfile as well, I can take a stab at poking through the source code and seeing if I can make the (hopefully minor) change required to support it as well.

**Comment by shankari** [comment]
I assume the fix is to expand the pattern here
https://github.com/sylvainhalle/textidote/blob/7b4604fdda14a0e4740654cd53e2df5b763eb504/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L78

**Comment by sylvainhalle** [comment]
Thank you for your proposed contribution. You are right: this is the line where `subfile` should be added next to input and include. I'll mark this as an enhancement for the next release.

**Comment by shankari** [comment]
ok so this fix is not going to be a one-liner. It turns out that `\subfile` requires the full path of the included file, not the relative path like `\include` does.

**Comment by shankari** [comment]
The options to fix this are:
- strip out the prefix (e.g. convert `chapters/chap1/chap1-section1.tex` to `chap1/chap1-section1.tex` in `fetchIncludes`.
   - However, we don't actually know the prefix in `LatexCleaner` since it is created directly with the annotated text.
   - and in the place where we do know the filename (`Main`), we don't know whether the file was added using `\include` or `\subfile` and needs to be stripped or not

@sylvainhalle any thoughts on the best structure for the changes? Or is this too complicated and you want to leave `\subfile` unsupported?

**Comment by sylvainhalle** [comment]
May I suggest we move this discussion to #131
