### ISSUE TITLE
Only 21 warnings in example,tex

### ISSUE THREAD

**Issue by Martinique-F** [sylvainhalle/textidote#116]
Hi! I just found your really interesting tool and am excited to try it out!
However, when I run the command 
textidote --output html example.tex > example.html

I just get 21 warnings.. I installed it using sudo. I attached a screenshot from the resulting html page.

Thanks for any help! 

![Screenshot from 2020-01-24 13-56-07](https://user-images.githubusercontent.com/54138776/73070704-50907780-3eb1-11ea-8461-e03be7668a40.png)

**Comment by sylvainhalle** [comment]
Hi! Thank you for your interest.

You are missing warnings because TeXtidote by default does not perform spelling and grammar checking. In order to do so, you must use the `--check` command line option. Please have a look at the Readme for more information.

Cheers!

Sylvain
