### ISSUE TITLE
\captionsetup is interpreted as a caption

### ISSUE THREAD

**Issue by phuhl** [sylvainhalle/textidote#117]
Nice tool, really helpfull. One tiny nitpick (not a big issue at all):

When using a `captionsetup` within a `wrapfigure`, it is interpreted as a caption that is lacking a period at the end.

![grafik](https://user-images.githubusercontent.com/16835755/73363761-a1391380-42a9-11ea-9a67-2bbe8cadc081.png)

The command I ran is:

```    textidote --check en --output html --dict textidote.dic.txt Hauptdokument.tex > report.html```

**Comment by sylvainhalle** [comment]
Thanks for your observation! This is actually something that can be easily be fixed. I'll mark it for the next release.
