### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by soli** [sylvainhalle/textidote#121]
Would it be possible to get a release at least including the overflow fix for `--output singleline`?

Thanks.

**Comment by sylvainhalle** [comment]
I know the 0.9 release is overdue, but I am doing this in my spare time. I'll do my best to prepare a new release in the weeks to come.

**Comment by soli** [comment]
Yeah, I can imagine it's not easy, but if 0.9 is too far, at least add a new 0.8.2 with what you got…

To give you context, I was trying to convert colleagues to use textidote, and they wanted a flycheck checker for Emacs, but `--output singleline` basically crashed every single time they used it, so…

**Comment by sylvainhalle** [comment]
I understand. I you can live with a release with minimal upgrades, I could do this more quickly. :-) Will add this to my todo list for this week.

**Comment by sylvainhalle** [comment]
Could you just remind me what is the issue that mentions this problem? I can't seem to find it.

**Comment by toolcreator** [comment]
I think it's #100

**Comment by soli** [comment]
Yep exactly, thanks @toolcreator ^^

**Comment by soli** [comment]
And I could definitely live with a minor release for now, thanks a lot !

**Comment by fakedrake** [comment]
Could you provide your `flycheck-define-checker` call @soli ?

**Comment by soli** [comment]
Actually it's mine, I haven't convinced anyone yet ;-)

```elisp
(flycheck-define-checker tex-textidote
    "A LaTeX grammar/spelling checker using textidote.

    See https://github.com/sylvainhalle/textidote"
    :modes (latex-mode plain-tex-mode)
    :command ("java" "-jar" (eval (expand-file-name "~/Dropbox/textidote.jar")) "--read-all"
              "--check" (eval (if ispell-current-dictionary (substring ispell-current-dictionary 0 2) "en"))
              "--no-color" source-inplace)
    :error-patterns (
                     (warning line-start "* L" line "C" column "-" (one-or-more alphanumeric) " "
                              (message (one-or-more (not (any "]"))) "]")))
```

**Comment by matzex** [comment]
I like using textidote! Thanks for your work on this @sylvainhalle! Any chance of getting a release out? I would like to use some of the changes this 0.8.1.

**Comment by soli** [comment]
Ok, will there be a release one day or should I consider this project dead and switch to using matze-dd/YaLafi?
No criticism, we all have our priorities, but it would be nice to know…

**Comment by sylvainhalle** [comment]
Done! Version 0.8.2 is now available and integrates all the bugfixes accumulated since 0.8.1.

**Comment by acorbe** [comment]
> Actually it's mine, I haven't convinced anyone yet ;-)
> 
> ```emacs-lisp
> (flycheck-define-checker tex-textidote
>     "A LaTeX grammar/spelling checker using textidote.
> 
>     See https://github.com/sylvainhalle/textidote"
>     :modes (latex-mode plain-tex-mode)
>     :command ("java" "-jar" (eval (expand-file-name "~/Dropbox/textidote.jar")) "--read-all"
>               "--check" (eval (if ispell-current-dictionary (substring ispell-current-dictionary 0 2) "en"))
>               "--no-color" source-inplace)
>     :error-patterns (
>                      (warning line-start "* L" line "C" column "-" (one-or-more alphanumeric) " "
>                               (message (one-or-more (not (any "]"))) "]")))
> ```

I think this snippet is pretty useful :). Thanks @soli . Perhaps it can be highlighted somewhere in the documentation?

**Comment by sylvainhalle** [comment]
Definitely; would you like to make a pull request with an updated version of the Readme?

**Comment by acorbe** [comment]
sure. see https://github.com/sylvainhalle/textidote/pull/186
