### ISSUE TITLE
Document the `--no-color` option in Readme

### ISSUE THREAD

**Issue by cphyc** [sylvainhalle/textidote#124]
Hi,
For the sake of parsing the output of textidote more easily, it would be useful to be able to remove colors from the output when using the `singleline` output mode.

**Comment by sylvainhalle** [comment]
Hi! You can already do this by using the `--no-color` command line switch. This argument is not mentioned in the Readme though!

**Comment by cphyc** [comment]
Great! That's indeed the solution to my issue. Should the issue be closed?
