### ISSUE TITLE
Build task for VSCode

### ISSUE THREAD

**Issue by cphyc** [sylvainhalle/textidote#125]
Thanks for the amazing tool! I have written a custom task to plug textidote into VS code.
Maybe this would be worth mentionning somewhere on the wiki?

```javascript
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
         [...],
         {
            "label": "Check LaTeX with textidote (LaTeX+language)",
            "type": "shell",
            // You can change the default language down there
            // The `sed` command is to strip the colours out of the output of textidote, see https://stackoverflow.com/a/18000433
            "command": "textidote --check en_UK --output singleline --no-color ${file}",
            "problemMatcher": {
                "fileLocation": "autoDetect",
                "severity": "warning",
                "pattern": [
                    {
                        "regexp": "^(.*)\\(L([0-9]+)C([0-9]+)-(L([0-9]+)C([0-9]+)|\\?)\\): (.*)$",
                        "file": 1,
                        "line": 2,
                        "column": 3,
                        "endLine": 5,
                        "endColumn": 6,
                        "message": 7
                    }
                ]
            }
        }
    ]
}
```

**Comment by toolcreator** [comment]
This was the whole purpose behind the singleline output, so it probably doesn't hurt to provide a vscode problem matcher somewhere. The regex is probably also helpful for people using other editors.

**Comment by DOFfactory** [comment]
I just discovered your project recently (yesterday), and I am looking around for a documentation, and would love to implement textidote into my LaTeX and Markdown workflows in vscode. Could you please elaborate where do I need to add these commands exactly? I would appreciate it.

**Comment by PierreMarchand20** [comment]
FYI I discovered this great extension that works for latex and markdown: https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex 

It does the job quite well and version 5 does not require any external dependency.

**Comment by DOFfactory** [comment]
@PierreMarchand20 thanks, works amazing. Still, I am also interested in textidote integration...

**Comment by sylvainhalle** [comment]
Thanks! I'll put a link to this thread inside the `Readme`.
