### ISSUE TITLE
doesn't recognise subequations from amsmath package

### ISSUE THREAD

**Issue by paddyroddy** [sylvainhalle/textidote#130]
I'm getting multiple warnings about repeated use of the word subequations. Is there a better way than disabling `lt:en:ENGLISH_WORD_REPEAT_RULE`? I'd rather not as that rule is very useful elsewhere

![image](https://user-images.githubusercontent.com/15052188/84939863-e209bb80-b0d6-11ea-8662-98a265e1e5f6.png)

**Comment by sylvainhalle** [comment]
This command-line switch is probably what you need: https://github.com/sylvainhalle/textidote#ignoring-environments

**Comment by paddyroddy** [comment]
ah yes I hadn't thought of that, it works cheers
