### ISSUE TITLE
Integration with LT

### ISSUE THREAD

**Issue by myravian** [sylvainhalle/textidote#135]
Hi there, 
I'm trying a few tools like textidote, but I can't seem to find how to make LT work with it (I have only latex-related corrections, spelling and grammar mistakes don't appear). Do you have to set up a path somewhere for the org directory or for the languagetool-commandline.jar? How does textidote find LT? Some more documentation on this would be useful in the readme. Also, I seem to have the same issue as others, with the ngrams check complaining about Lucene (Could not load codec 'Lucene410'.  Did you forget to add lucene-backward-codecs.jar? N-gram rules will be ignored.).
Cheers,
MV

**Comment by sylvainhalle** [comment]
Hi! Regarding your first question, LT is bundled within the TeXtidote jar, so it should work out of the box with the `--check XX` command line parameter. As for the second issue, it has been pending for a long time and it shall be fixed once the next release of TeXtidote includes an updated LT bundle. Hopefully soon!

**Comment by myravian** [comment]
Ok thanks! Since the first issue wasn't normal, I looked some more and saw somebody had this issue as well, which is fixed by using --read-all (it was used on the excerpt of a manuscript). 
Thanks and great work, this is quite pleasant to use.

**Comment by sylvainhalle** [comment]
Thanks for these kind words!
