### ISSUE TITLE
Optional macro arguments may cause false positive

### ISSUE THREAD

**Issue by bratekarate** [sylvainhalle/textidote#141]
### Bug Description
For some macros (only observed with `\parencite` so far), optional arguments in brackets cause false positives in the LanguageTool checks. Example:

`\parencite{source}` yields no errors.
`\parencite[p. 12-24]{source}` yields: 
```
--(L8C704-L8C713): Possible spelling mistake found. Suggestions: [parents, parent, precise, parasite, parentage, parenting, recite, Prentice, Principe, parented, parricide, partite, perennate, martensite, pargasite, potentite, variscite] (729)
```
... I like the parasite suggestion though. They should add that macro to latex :)

### Temporary workaround
Use command line argument (or config file) `--remove-macros parencite` (thanks for adding this flag, great for such cases!)

**Comment by sylvainhalle** [comment]
The culprit is https://github.com/sylvainhalle/textidote/blob/ba5694c3e1868ee861ab24f640f3f8c81e23141e/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L382, which should be changed to handle the case where square brackets are present before the curly brackets.

**Comment by sylvainhalle** [comment]
As a matter of fact, `parencite` should be handled like other `cite` commands, so the fix is not where I said it should be
