### ISSUE TITLE
Latex markup cleaning fails if line begins with math

### ISSUE THREAD

**Issue by lorenzhs** [sylvainhalle/textidote#145]
The cleaning of latex markup gets confused if a line starts with math mode and contains some more math later, e.g.:

```latex
Consider the following: Let
$x=7$ and (blah blah) $y=5$ in the above formula.
```

The cleaning process mangles this and eats the middle part, `and (blah blah)` completely. Instead, it outputs parts of the two math bits.

**Comment by sylvainhalle** [comment]
I suspect this line:
https://github.com/sylvainhalle/textidote/blob/9cd25a648074314f9b8cef91c47972913aed0a26/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L413
and the following should be done first, instead of last
