### ISSUE TITLE
Is it possible to let the check starting from \begin{document}

### ISSUE THREAD

**Issue by wenlzhang** [sylvainhalle/textidote#150]
Before `\begin{document}`, it might give some checked errors in package loading part, which may not be necessary. Therefore, is it possible to let the check starting from `\begin{document}`? Or is there a workaround to avoid checking unnecessary package name or the entire package loading command?

**Comment by sylvainhalle** [comment]
The Readme says:

> By default, TeXtidote ignores everything before the `\begin{document}` command. [...]

Reading before `\begin{document}` only happens if you use the command line option `--read-all`.
