### ISSUE TITLE
TeXtidote allows LanguageTool to proofread inside backtick quotes

### ISSUE THREAD

**Issue by oblitum** [sylvainhalle/textidote#152]
~~TeXtidote causes LanguageTool to proofread inside triple backtick blocks in Markdown files. This is not the LanguageTool default behavior, which will ignore content in such blocks, which are used for code. LanguageTool does warn about the backticks themselves ("Use a smart opening quote here"), no idea why.~~\

TeXtidote allows LanguageTool to proofread inside backtick quotes in Markdown files. This is the LanguageTool default behavior, which doesn't ignore contents in such quotes and even suggests replacing such quotation for other kind. TeXtidote should handle that I think?

**Comment by sylvainhalle** [comment]
I tested with this input file:

    Hello, my name is Bill.
    
    ```
    foobar
    ```
    
    What about you?

I got no error for the part between backticks. Could you please post a minimum working example that reproduces the issue?

**Comment by oblitum** [comment]
Never mind, this was a mistake on my part. The actual issue is with single backticks, it will point spelling error for command like

```md
`sysctl`
```

But it happens in both tools (`languagetool -l en-US`, `textidote --check en_US`). Shouldn't TeXtidote stop proofreading there?

**Comment by sylvainhalle** [comment]
I think that if LT analyzes what is between backticks, TeXtidote should do the same in order to be consistent.

**Comment by oblitum** [comment]
Okay, I just think it doesn't make sense to proofread inside code quotes, it should be excluded just like inside LaTeX formulas?

**Comment by sylvainhalle** [comment]
It's true that in the LaTeX cleaner, the equivalent command (`\verb+`) is replaced by a dummy placeholder. The same could be done for Markdown with single ticks.
