### ISSUE TITLE
--replace not documented

### ISSUE THREAD

**Issue by Sh3Rm4n** [sylvainhalle/textidote#156]
The replacemant option is briefly mentioned in the README.

https://github.com/sylvainhalle/textidote/blob/master/Readme.md#L324

But it is not documented anywhere (at least i could'nt find any). 
Briefly reading through the source-code did not make me smarter about how to use this feature. 

Anyway! Thanks for this useful tool. Really improves my proofreading experience with latex files! 👍

**Comment by sylvainhalle** [comment]
Indeed! I'll add a mention to this feature in the Readme.
