### ISSUE TITLE
NullPointerException with --check

### ISSUE THREAD

**Issue by krsch** [sylvainhalle/textidote#16]
When I run `textidote.jar --html --check en my.tex` I get
```
TeXtidote v0.4 - A linter for LaTeX documents
(C) 2018 Sylvain Hallé - All rights reserved

Exception in thread "main" java.lang.NullPointerException
	at ca.uqac.lif.textidote.rules.CheckLanguage.evaluate(CheckLanguage.java:160)
	at ca.uqac.lif.textidote.Linter.evaluateAll(Linter.java:131)
	at ca.uqac.lif.textidote.Main.mainLoop(Main.java:314)
	at ca.uqac.lif.textidote.Main.main(Main.java:89)
```
It seems that this line is wrong:
https://github.com/sylvainhalle/textidote/blob/11caaf3fca18afc66b1b3fa8e85a8e2714436afb/Source/Core/src/ca/uqac/lif/textidote/rules/CheckLanguage.java#L132
It should initialize variables with `Position.NOWHERE`, not `null`

**Comment by JorricksTU** [comment]
I think your command is wrongly formulated. The docs state it should be the following:

Java - jar textidote.jar --check en --html example.tex > report.html

Could you try the above command please?

**Comment by krsch** [comment]
I think you meant
```
java -jar textidote.jar --check en --html example.tex > report.html
```
It works for `example.tex`, but it doesn't work for my document. I have tried to create a minimal test and came up with this:
```latex
\documentclass{article}
\usepackage{biblatex}
\begin{document}
\printbibliography%
\end{document}
```
It compiles with latex, but textidote fails with the I mentioned in the original message no matter if I run it with `java -jar ./textidote.jar --check en --html my.tex > report.html` or `./textidote.jar --check en my.tex`. After the change I proposed everything works fine. I can submit it as a pull request if needed.

**Comment by sylvainhalle** [comment]
@krsch Thanks for your example. Indeed, changing `null` to `NOWHERE` is the solution, but it also triggers a few changes in some other files. My next commit should fix the issue. Please feel free to reopen if the problem is still there (seems to work on my side)!

**Comment by krsch** [comment]
Thanks! Everything works on my documents.
