### ISSUE TITLE
Problems with \, and ~

### ISSUE THREAD

**Issue by pkel** [sylvainhalle/textidote#160]
Thanks for your great work. Textidote is a relief.

I ran into problems when using `~` and `\,` like in the following example.

```latex
\documentclass{article}
 
\begin{document}
I want to demo a small textidote bug regarding white space. It seems that \verb|\,| and \verb|~| are not recognized as such, e.\,g.~this should be fine.
 
It shows up when I cite Someone et al.~\cite{someone2020} or add a small space between a number and a unit as in 100\,\%. By the way, I think this last sentence is parsed as comment.
\end{document}
```

Do you consider this a bug or should I adapt?

I'm running textidote v0.8.1 from the jar file provided on the release page.

**Comment by sylvainhalle** [comment]
Thanks for your post. This could easily be added to the next version (note to myself: replace both symbols into spaces at the cleaning step).

**Comment by ErikBjare** [comment]
Not sure if this is as intended (so holding off on creating an issue), but I get warnings for `blablabla Fucci et al.~\cite{fucci_2019} blablabla`. Isn't this best-practice?

**Comment by sylvainhalle** [comment]
Could be handled by changing this line:

https://github.com/sylvainhalle/textidote/blob/ceb43e4bcdb9b972ec481bf2a1a6a01b6bdefd10/Source/Core/src/ca/uqac/lif/textidote/rules/regex.csv#L7

replace `[^\\,]` by `[^\\,~]`.
