### ISSUE TITLE
Char encoding option not working 0.8.1

### ISSUE THREAD

**Issue by csrabak** [sylvainhalle/textidote#161]
Using v0.8.1 in environment Windows 10 Home Single Language edition, version 2004, java version 1.8.0_261, when option --encoding is issued in the command line instead of analyzing the file, textidote shows a help screen.

Symptomatically the help screen does not mention "encoding" option at all.

Nowadays LaTeX has made utf-8 default, being able to parse UTF-8 files in Windows is not a pet option but more and more a necessity.

Is it an issue specific to the environment or am I using a wrong way of setting the option?

I attempted two ways: 
a) in command line;
b) in .textidote

The way I did was "--encoding utf-8", also tried UTF-8 instead, with no avail.

Since this feature is documented in the Readme.md, I _think_ it may be well considered a "bug".

--
Cesar Rabak

**Comment by sylvainhalle** [comment]
The encoding option is available if you compile from the latest sources. It is not present in 0.8.1. It will be included in the next release.

**Comment by csrabak** [comment]
OK.
Just to manage my time and effort do you have a expected schedule for the 0.8.2 release?

Thanks

**Comment by sylvainhalle** [comment]
Unfortunately no. Hopefully I'll be able to compile a new version with a few fixes some time this Winter, but I'm doing this in my spare time and I am totally swamped with work duties at the moment.
