### ISSUE TITLE
Meaning of the name TeXtidote

### ISSUE THREAD

**Issue by s1mahoeg** [sylvainhalle/textidote#164]
Hi, as a non-native english speaker I have two questions regarding the project name:

- How is TeXtidote pronounced?
- Does TeXtidote mean anything special? I only found some definition for the word `idote` at urbandictionary.com:
  `Idote is a word not so commonly used it means the same thing as stupid, idiot, dumb, baka, fool, imbecile, and bodoh,`

Maybe it's worth to put those information also in the readme?

**Comment by sylvainhalle** [comment]
Hi! Thanks for asking. For your information, TeXtidote is a play on _Antidote_, which is a spelling/grammar checker well known to French-speaking users and works with word processors. So TeXtidote is like a version of Antidote for TeX.

As for the pronunciation, I have no idea... may just say "antidote" and replace "anti" with "tex". That's how I would say it anyway.

I'll put this in the Readme!

**Comment by s1mahoeg** [comment]
Thanks for the quick feedback!
