### ISSUE TITLE
Be able to ignore lines

### ISSUE THREAD

**Issue by daniel-vera-g** [sylvainhalle/textidote#168]
I've been having some situations, where it would be helpful to be able to disable lines from linting.
For example having:

```md
Ignore a `.txt` file.
```

Get's me something like:

* L21C6-L21C7 Use 'an' instead of 'a' if the following 
  word starts with a vowel sound, e.g. 'an article', 'an hour'. Suggestions: 
  [an] (518) [lt:en:EN_A_VS_AN] 
  uses a `.txt` file

It's reasonable, so I would like to ignore it.  
I saw in the code, that there is an approach: https://github.com/sylvainhalle/textidote/blob/master/Source/Core/src/ca/uqac/lif/textidote/cleaning/markdown/MarkdownCleaner.java#L33

```md
<!-- textidote: ignore begin -->
A documnt.
<!-- textidote: ignore end -->
``` 

Nevertheless, in the code `MarkdownCleaner.java` they're never used and using it as above has no effect.

Is there some flag to activate it or can it be fixed? If it's not that complicated, I could look into it.

**Comment by sylvainhalle** [comment]
Indeed, what should be done here is the same as in `LatexCleaner`:

https://github.com/sylvainhalle/textidote/blob/7791f79732494a9337f7c90a6e91a06a1935180b/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L265

**Comment by daniel-vera-g** [comment]
Yeah, seems not to be complicated.
Will try to implement it & open an PR  :+1:
