### ISSUE TITLE
Support for \autoref

### ISSUE THREAD

**Issue by ModischFabrications** [sylvainhalle/textidote#169]
Using `\autoref{}` from the hyperref package seems to be a common suggestion for newcomers, but is currently not supported by texidote. 

Examples: 
```
\label{fig:line_overlay}
...
\autoref{fig:line_overlay}
```

This results in both a warning for the label that no reference was found and an error for the tag name of the autoref, that is analysed as if it was a german text. 

I tested it using ` textidote --check de --output html main.tex > report.html` on v0.8.2

**Comment by sylvainhalle** [comment]
Indeed, it can easily be done by adding `autoref` to the list of commands on this line:

https://github.com/sylvainhalle/textidote/blob/67e3f6eba9ce91639a48303c24a6b906f1250333/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L357
