### ISSUE TITLE
[FeatureRequest] Ignore additional commands, more precise some of their parameters

### ISSUE THREAD

**Issue by atticus-sullivan** [sylvainhalle/textidote#171]
Hi,

would it be possible to include a feature that makes it possible to exclude some macros/commands from the checking. Being more precise, I'm searching an equivalent feature to `atool`s `add-tex-command <macroname> <sensitivityListOfParameters>` (c.f. [http://aspell.net/0.50-doc/man-html/4_Customizing.html#4](http://aspell.net/0.50-doc/man-html/4_Customizing.html)).

I hope, I just didn't found that feature up to now.

**Comment by sylvainhalle** [comment]
Part of this can be achieved using the option to replace patterns, see https://github.com/sylvainhalle/textidote#replacing-strings. In this case the replacement would be a dummy or empty string.

However, while Aspell parses LaTeX, TeXtidote does not (and will not, see https://github.com/sylvainhalle/textidote/issues/56). This means that you cannot _reliably_ specify such thing as "skip the first two parameters of the command", as you can do with Aspell. The best you can achieve is a regular expression that matches opening/closing braces, but this will break if arguments themselves contain nested commands, etc.

**Comment by atticus-sullivan** [comment]
Ok, alright, thanks for the clarification :+1:
