### ISSUE TITLE
XGBoost on windows warning - can I add it

### ISSUE THREAD

**Issue by lfdversluis** [sylvainhalle/textidote#177]
Thanks a lot for this great tool! It works really well. I was wondering, I get the warning on Windows `At the moment, your platform (Windows) is not supported by the official  XGBoost maven package; ML-based suggestion reordering is disabled.` These suggestions sounds interesting. Is there a way to enable them on Windows? Would adding XGBoost (somehow?) to the system path do the trick?

If there is no easy way, I guess subsystem for windows or just a linux machine will have to do :)

**Comment by sylvainhalle** [comment]
Hi! This is an issue with the LanguageTool library that is used by TeXtidote: https://forum.languagetool.org/t/how-to-silence-windows-warning-about-xgboost/4887

So unfortunately, there is not much I can do on my side.
