### ISSUE TITLE
--remove-macros doesn't seem to do anything

### ISSUE THREAD

**Issue by JoeyEremondi** [sylvainhalle/textidote#180]
Input:
```
$ cat test.tex
\begin{document}
\foo{Hello worlf!}
\end{document}
```

Command run: `textidote --remove-macros foo  --read-all --check en  test.tex`

Expected output: no errors found

Actual output: 
```
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain Hallé - All rights reserved

Found 1 warning(s)
Total analysis time: 2 second(s)

* L2C12-L2C17 Possible spelling mistake found. Suggestions: [world, wolf,
  Wolf, Woolf] (6) [lt:en:MORFOLOGIK_RULE_EN_US]
  \foo{Hello worlf!}
             ^^^^^^
```

I suspect I'm just doing something wrong, but as far as I can tell, the \foo macro isn't being removed at all.
Am I doing something wrong? Or is this a bug?
Thanks!

**Comment by sylvainhalle** [comment]
I'm not sure to understand. `foo` does not seem to be present at all in the input file?

**Comment by JoeyEremondi** [comment]
Ah shoot, I pasted the wrong thing. Sorry.

I've updated the initial post with the actual file.

**Comment by sylvainhalle** [comment]
Thanks, I confirm I can reproduce the bug.

**Comment by sylvainhalle** [comment]
Found the culprit, will push a modification that fixes it.

**Comment by JoeyEremondi** [comment]
Wow, thanks!

**Comment by MatthiasLohr** [comment]
I guess, since the last version is from March 31, this fix is not officially released yet? I'm having the same problem here.

**Comment by sylvainhalle** [comment]
That's right, you can build the tool from the sources, otherwise the fix will be present in the next release.

**Comment by MatthiasLohr** [comment]
When are you planning to do the next release?

**Comment by sylvainhalle** [comment]
Probably some time in September
