### ISSUE TITLE
different results in macOS and Linux

### ISSUE THREAD

**Issue by peshay** [sylvainhalle/textidote#181]
Hi! I like to use textidote for my current project within travis-ci. If I run it on macOS with java 
```
java 16.0.1 2021-04-20
Java(TM) SE Runtime Environment (build 16.0.1+9-24)
Java HotSpot(TM) 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```
Then I get a lot of warnings
```
java -jar ~/Downloads/textidote.jar --check de thesis.tex
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain Hallé - All rights reserved

Found 63 warning(s)
Total analysis time: 6 second(s)
```
But if I run it with ubuntu hirsute in docker, I get 0 Warnings on the same file
```
java -jar textidote.jar --check de thesis.tex
TeXtidote v0.8.2 - A linter for LaTeX documents and others
(C) 2018-2021 Sylvain Hall? - All rights reserved

Found 0 warning(s)
Total analysis time: 4 second(s)

Everything is OK!
```
Here all commands I used to setup docker `docker run -it ubuntu:hirsute bash`
```
apt-get -qq update
apt-get install -y texlive-base texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-lang-german texlive-bibtex-extra texlive-fonts-extra wget openjdk-16-jdk
wget https://github.com/sylvainhalle/textidote/releases/download/v0.8.2/textidote.jar
```
Any idea what I miss here?

**Comment by sylvainhalle** [comment]
Unfortunately I don't have access to a Mac machine... could you perhaps post a short TeX file that shows an example of the difference, and also what warnings are triggered by it?

If I were to guess, I would say this is something related to either file encoding, or carriage returns (which differ between Linux and Mac).

**Comment by peshay** [comment]
I think to you don't need to macOS to test. In my opinion with macOS it works just fine. I now tested it with ubuntu focal and here it works the same way as on macOS. So the question is, why is it not showing issues in hirsute? But since I know just switched to ubuntu focal on my testing, you can also close the issue for me. But if you're interested on the different behavior of those two OS: 
You can test and compare with `docker run -it ubuntu: focal bash`.

**Comment by sylvainhalle** [comment]
You mean it does not show _any_ warning with _any_ file?

**Comment by peshay** [comment]
Yes that was actual the case.. but I am not able to reproduce it anymore with hirsute vs focal. Since everything works now for me with focal, I will close this issue.
