### ISSUE TITLE
Arabic Language support

### ISSUE THREAD

**Issue by linuxscout** [sylvainhalle/textidote#188]
Hi, 
The Arabic language is supported in LanguageTool since version 4.9 (2020-03-24),
Is there any plan to support it for Textidote?
I'm a member of arabic support team for Languagetool/
thanks

**Comment by sylvainhalle** [comment]
Yes, definitely. In the next planned release (0.9), I intend to upgrade the version of LanguageTool bundled inside TeXtidote to 5.x. It should then be just a matter of adding Arabic to the list of languages in the command line parameters here:

https://github.com/sylvainhalle/textidote/blob/a779f7978e513c32831de86232775253371179a0/Source/Core/src/ca/uqac/lif/textidote/rules/LanguageFactory.java#L47

**Comment by linuxscout** [comment]
Thank you a lot. I will be happy for that.
