### ISSUE TITLE
Math is not detected/replaced in Markdown

### ISSUE THREAD

**Issue by bvolkmer** [sylvainhalle/textidote#191]
The replacements for inline and display math is not working for Markdown.

`--clean` yields not change on the following example text, leading to errors from LanguageTool

```
This is a test: $a^2+b^2=c^2$ or \(a^2+b^2=c^2\).

$$a^2+b^2=c^2$$

\[a^2+b^2=c^2\]
```

For combination with `pandoc` a solution for the $-style math would be preferable

Version: v0.8.2

**Comment by bvolkmer** [comment]
Also, `--replace` does not seem to work at all for Markdown.

`--replace replacments.txt`:
```
an a
```
on `test.md`:
```
This is an test.
```
Returns the error: `Use 'a' instead of 'an'...`

So the original issue can't be worked around with `--replace`

**Comment by sylvainhalle** [comment]
I cannot reproduce this bug. As mentioned in the readme, could you double-check that the strings are separated by a **tab** in `replacements.txt`?

**Comment by sylvainhalle** [comment]
As for your first comment, TeXtidote does not expect LaTeX markup in a Markdown file, so what happens is the expected behavior.

**Comment by bvolkmer** [comment]
You are right, I didn't use tabs. That is working.
I'll fiddle with `--replace` then.

**Comment by bvolkmer** [comment]
Maybe as clarification for the README:
Replace rules are applied line wise as far as I see. So for my case multiline display math regex won't work.
`\$\$(.|\n)+?\$\$`

**Comment by sylvainhalle** [comment]
Yes indeed. I added a remark in the readme.
