### ISSUE TITLE
\" raising warning about not using "

### ISSUE THREAD

**Issue by neil-lindquist** [sylvainhalle/textidote#195]
`\"` is used to apply an umlaut-type accent; however, it gets caught by the warning to not use `"`.  For example `na\"{\i}ve` gets flagged, even though its the only way to write naïve with the accent.

I think it should just be a matter of changing the regex in [line 9 of regex-detex.csv](https://github.com/sylvainhalle/textidote/blob/master/Source/Core/src/ca/uqac/lif/textidote/rules/regex-detex.csv#L9) to `(?<!\\)"`.  But I don't have ant installed, so I can't test it.

Also, the following tests for that regex could be added to [CheckRegexTest.java](https://github.com/sylvainhalle/textidote/blob/master/Source/CoreTest/src/ca/uqac/lif/textidote/rules/CheckRegexTest.java).
```java
	@Test
	public void testD008_1()
	{
		AnnotatedString in_string = AnnotatedString.read(new Scanner("Hello \"World\""));
		Rule r = m_detex_rules.get("sh:d:008");
		List<Advice> ad_list = r.evaluate(in_string, in_string);
		assertEquals(2, ad_list.size());
	}

	@Test
	public void testD008_2()
	{
		AnnotatedString in_string = AnnotatedString.read(new Scanner("na\\\"{\\i}ve"));
		Rule r = m_detex_rules.get("sh:d:008");
		List<Advice> ad_list = r.evaluate(in_string, in_string);
		assertEquals(0, ad_list.size());
	}
```

**Comment by sylvainhalle** [comment]
Thanks for your suggestion. I will incorporate it in the code shortly.
