### ISSUE TITLE
Can I prevent grammar checks on \citet{} and \citep{} arguments?

### ISSUE THREAD

**Issue by richard-herron** [sylvainhalle/textidote#201]
Thanks for textidote!

I use `\citet{}` and `\citep{}` citation commands, and one of my .bib files has labels like  `Last1.Last2.YYYY`. When I use `--check en` to grammar check my .tex files, LanguageTool highlights that my .bib file labels are grammatically incorrect, and textidote highlights that my .bib file labels do not have spaces after periods. If I remove `--check en`, I do not receive either feedback.

Is there a way to prevent LanguageTool from checking .bib file labels? 

Here is an MWE:

temp.tex:

```  
\documentclass{article}

\usepackage{natbib}
\bibliographystyle{apalike}

\begin{document}

\citet{Coiculescu.Izhakian.Ravid.2019} find X, Y, and Z.

\bibliography{temp}

\end{document}
```

temp.bib:
  
```
@ARTICLE{Coiculescu.Izhakian.Ravid.2019,
  author = {Gabriela Coiculescu and Yehuda Izhakian and S. Abraham Ravid},
  title = {Innovation under Ambiguity and Risk},
  note = {3428896},
  year = {2019},
  journal = {SSRN eLibrary},
  location = {http://ssrn.com/paper=3428896}
}
```

I use the following textidote call: `textidote --no-config --output html --check en temp.tex > temp.html`

And here is the output:

![image](https://user-images.githubusercontent.com/2307622/151672950-df5fbfd0-0ced-4127-9344-8a7eac31ecbe.png)

**Comment by sylvainhalle** [comment]
The culprit is this line:

https://github.com/sylvainhalle/textidote/blob/70620548a1a98b71ed5b26643c89835bd7bdadfb/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L322

It handles a few variants of `\citeX`, but not `\citet`. I'll change this for the next release.

**Comment by maltegrosse** [comment]
perhaps \cite* wildcard? (i am using \citealp too)
