### ISSUE TITLE
[sh:d:002] rule triggers inside \verb

### ISSUE THREAD

**Issue by dipzza** [sylvainhalle/textidote#208]
Using v0.8.3 release,

Console output of análisis:
```
* L58C304-L58C320 There should be a space after a period. If you are writing a 
  URL or a filename, use the \url{} or \verb markup. [sh:d:002] 
  as que el archivo \verb|poetry.lock| pero en un fo
```
Also fails without delimiter:
```
* L41C72-L41C84 There should be a space after a period. If you are writing a 
  URL or a filename, use the \url{} or \verb markup. [sh:d:002] 
  a herramienta \verb Coverage.py para garantizar qu
```

Probable cause is that the \verb command uses a non-standard syntax, instead of being opened and closed by {} it can use **any** symbol as an opening / closing delimiter, which seems problematic. I solved my problem by using --remove-macros for \texttt{}.

Perhaps if it is difficult to implement the use of \verb the advice given could be changed to another option?

**Comment by sylvainhalle** [comment]
I think this should be doable by changing the regex pattern here:

https://github.com/sylvainhalle/textidote/blob/4ecf475ad33a0e4a9315596c0c5d943f68909cc1/Source/Core/src/ca/uqac/lif/textidote/cleaning/latex/LatexCleaner.java#L324

to:

```
\\\\verb(.).*?\\1
```

**Comment by dipzza** [comment]
Nice :) I'm working on this if that's fine.

For now i have the following pattern:
`\\\\verb\\*?(\\S).*?\\1` 

Is a little more precise and also covers the \verb* char text char [sintax](https://www.typeerror.org/docs/latex/_005cverb)

When i test is working fine i will open a PR
