### ISSUE TITLE
[question] /opt/textidote or /usr/share/java/textidote ?

### ISSUE THREAD

**Issue by Freed-Wu** [sylvainhalle/textidote#210]
This package is installed in `/opt/textidote` (for textidote.deb). However, in Linux, All software written by java should be installed `/usr/share/java`. Such as:

```shell
❯ ls /usr/share/java
 brlapi.jar   jxrlib-0.2.4.jar   languagetool   libbluray-awt-j2se-1.3.1.jar   libbluray-j2se-1.3.1.jar   opencv.jar   opencv4   pdftk   textidote.jar   turbojpeg.jar   vtk
```

A reasonable directory structure is:

```
textidote-bin /etc/
textidote-bin /etc/bash_completion.d/
textidote-bin /etc/bash_completion.d/textidote
textidote-bin /usr/
textidote-bin /usr/bin/
textidote-bin /usr/bin/textidote
textidote-bin /usr/bin/textidote-desktop
textidote-bin /usr/share/
textidote-bin /usr/share/applications/
textidote-bin /usr/share/applications/textidote.desktop
textidote-bin /usr/share/java/
textidote-bin /usr/share/java/textidote.jar
textidote-bin /usr/share/man/
textidote-bin /usr/share/man/man1/
textidote-bin /usr/share/man/man1/textidote.1.gz
textidote-bin /usr/share/textidote/
textidote-bin /usr/share/textidote/textidote-icon.svg
textidote-bin /usr/share/zsh/
textidote-bin /usr/share/zsh/site-functions/
textidote-bin /usr/share/zsh/site-functions/_textidote
```

(And `/usr/share/applications/textidote.desktop` should be provided.)

Thanks!

**Comment by sylvainhalle** [comment]
Thanks for telling me, I didn't know about this convention.

**Comment by sylvainhalle** [comment]
Actually, I will close this issue, as /usr/share/java is Java's *classpath*, i.e. the folder where Java programs look for libraries. TeXtidote is not a library; it is a stand-alone program, that just happens to be written in Java.

For example, [JabRef](https://www.jabref.org/) is written in Java, and on my machine it is not installed in /usr/share/java, but in the /opt folder.

**Comment by Freed-Wu** [comment]
<https://wiki.archlinux.org/title/Java_package_guidelines#Introduction>

**Comment by sylvainhalle** [comment]
Thanks, but these guidelines are specific to Arch, and I don't create packages for this distribution.

Rationale for using `/opt`: https://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html
