### ISSUE TITLE
Getting started with textidote

### ISSUE THREAD

**Issue by Mark-McCormick** [sylvainhalle/textidote#212]
I am trying to do a first time manual install of textidote.

So far I am able to view the jar file using 7-zip. What are the next steps in detail and for dummies?

Will you please direct me to basic getting started instructions?

Considering that many LaTeX users might not know anything about Java (like me), I think that the instructions must already exist somewhere. But where?

**Comment by Mark-McCormick** [comment]
Due to lack of effort on my part, I did not solve the problem.

You may close the issue.
________________________________
De : Sylvain Hallé ***@***.***>
Envoyé : mardi 28 février 2023 20:57
À : sylvainhalle/textidote ***@***.***>
Cc : Mark Mc Cormick ***@***.***>; Author ***@***.***>
Objet : Re: [sylvainhalle/textidote] Getting started with textidote (Issue #212)


Did this solve your problem? Can I close the issue?

**Comment by sylvainhalle** [comment]
I am sorry to hear that, but given the very limited time I have to work on this project, I will close the issue for now.

If anybody is willing to help @Mark-McCormick, you are most welcome.
