### ISSUE TITLE
code missing

### ISSUE THREAD

**Issue by san59deep** [sylvainhalle/textidote#213]
hello sir,
I went through your java program but there was a issue, some files were missing and was not able to run the java program [linter.java class "getname() and evaluate()" is missing] can you please provide the missing code to run the program

**Comment by sylvainhalle** [comment]
I am afraid there is an issue with the setup on your local machine. As you can see here (https://app.travis-ci.com/github/sylvainhalle/textidote), the latest build was done three days ago from the contents of the GitHub repository and everything compiles.

Are you trying to *build* the tool, or simply *run* it? In the first option, I recommend using the Ant script that does all the job for you. In the second option, I strongly recommend you simply download the pre-compiled jar file and run it as instructed in the Readme.

**Comment by san59deep** [comment]
Is it possible to modify the code and use it for commercial purpose?
