### ISSUE TITLE
Is it possible to modify the code and use it for commercial purpose?

### ISSUE THREAD

**Issue by san59deep** [sylvainhalle/textidote#214]
Is it possible to modify the code and use it for commercial purpose?

_Originally posted by @san59deep in https://github.com/sylvainhalle/textidote/issues/213#issuecomment-1255831768_

**Comment by sylvainhalle** [comment]
The software is distributed under the GNU General Public License, see the details here: https://github.com/sylvainhalle/textidote/blob/master/LICENSE

However, if you plan on integrating TeXtidote into some commercial product, I'd appreciate if you let me know. It is always nice to know who uses your stuff.
