### ISSUE TITLE
About latest release

### ISSUE THREAD

**Issue by chenrui333** [sylvainhalle/textidote#219]
👋 it looks like the 0.9 did not get marked as latest release. Just create this issue to raise some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/125168

**Comment by sylvainhalle** [comment]
It is a preview release I put online to check something with a user about issue #218. It is not yet the official release and future changes are expected.

**Comment by chenrui333** [comment]
I see, thanks!
