### ISSUE TITLE
For manual download, the language tool check doesn't work.

### ISSUE THREAD

**Issue by kanitw** [sylvainhalle/textidote#25]
I wonder if it's because textidote couldn't find the `languagetool`'s jar. 

> You can also download the TeXtidote executable manually: this works on all operating systems. Simply make sure you have Java version 8 or later installed on your system. Then, download the latest release of TeXtidote; put the JAR in the folder of your choice.

Is there any instruction for where to put the `languagetool`?  

(Note that I'm doing manual download as I'm using a Mac, not Linux.) 

Thank you.

**Comment by sylvainhalle** [comment]
Hi! Could you be more explicit when you say that it can't "find" Language Tool? Are you getting an error message of some kind?

If you are doing the manual install, the file you need to download is the big JAR associated to a specific release, such as this one:

https://github.com/sylvainhalle/textidote/releases/download/v0.4/textidote.jar

This JAR already includes Language Tool inside, so there is no need to download anything else. Then, simply run
```
java -jar path/to/textidote.jar (etc.)
```

Could you confirm that this works for you?

**Comment by kanitw** [comment]
Apologies. I just discovered I need to use `--read-all` flag for my subfiles. 

Thanks a lot for making this tool available!

**Comment by sim590** [comment]
Regarding this, I have come across the same difficulty and I concede the fact that you mention the option `read-all` in the README file, but documentation for `--read-all` is far from clear in this matter.

> Don't ignore lines before \begin{document}

The way it's written, it says that it will read **before** `\begin{document}`. Can you write the documentation about `--read-all` more consistent with the use case of sub-files ? May be something like 

> Don't ignore files without \begin{document} and read the whole file

Or something along the same lines?

Thanks for your program by the way. I'm trying it out right now.
