### ISSUE TITLE
Screenshot does not correspont command

### ISSUE THREAD

**Issue by tildemy** [sylvainhalle/textidote#29]
Hi.

A small correction, the screenshot under your description for HTML report does not correspond to the command in the section.

Command: $ textidote --html example.tex > report.html
Screenshot: $ textidote --check en --html example.tex > report.html

**Comment by sylvainhalle** [comment]
Agree, but the text says "you should see *something like* this". The point is just to show people the kind of output they should expect, and I think this is close enough. I'll close this as "wontfix" but keep this in mind in case I change the screenshot some day.
