### ISSUE TITLE
how it works on Windows

### ISSUE THREAD

**Issue by Ferasalkam** [sylvainhalle/textidote#43]
Many thanks for the great tool.
I am a Windows user. I tried to run it as described i.e. install example.tex and the textdote.jar in the same folder and try to run the command from Texmaker user command. It says "Error : could not start the command : $ java -jar textidote.jar --html example.tex > report.html"

Could you please support me?

Many thanks in advance

best regards

Feras

**Comment by sylvainhalle** [comment]
Hi! Thanks for your comment. Does your command include the dollar sign? If so, try removing it; it is only there to represent the command line prompt and should not be typed, actually.

**Comment by Ferasalkam** [comment]
Many thanks for your support.
I have tried it works now but with error

"TeXtidote v0.6 - A linter for LaTeX documents and others (C) 2018 Sylvain Hall� - All rights reserved
File > not found (skipping)
File report.html not found (skipping) Found 4 warning(s) Total analysis time: 0 second(s)
Process exited with error(s)"

could you please help solving that?

best regards

Feras

**Comment by sylvainhalle** [comment]
It looks like your software does not recognize the `>` character, which means "redirect `stdout` to a file"; it tries to interpret it as a filename. This is not an issue with TeXtidote, but rather with Texmaker. I encourage you to forward your question to a help forum for this software. Good luck!

**Comment by GitHubRulesOK** [comment]
For other window users with a similar problem the simplest way to avoid pathing errors is to write a small 2 line "grammar.cmd" file and place it in the **java\bin** directory (java is then the focus of its own file paths). For example my java and TeXtidote are on a usb stick along with MiKTeX/TeXworks  so you will need to edit this example accordingly for your own program folders.

grammar.cmd
```
"h:\java\bin\java.exe" -jar "h:\textidote\textidote.jar" --html --check en  "%1" >report.html
report.html
```
Note the second line sends report.html to the default browser If you wish it to go to another browser you would need to add that "browser.exe" to the start of the second line 

In TeXworks it is easy to ad another "typeset that calls the grammar.cmd passing $fullname as the current .tex file argument here is a screenshot
![grammar](https://user-images.githubusercontent.com/12754913/51095521-4c655080-17ad-11e9-8b9c-0e04c7d260f7.png)

**Comment by Foadsf** [comment]
Just downloaded the software on windows 10.  tried running the .jar file by double-clicking on it. but it doesn't do anything!

**Comment by copyme** [comment]
@Foadsf I suggest to read the documentation and then you should try running the tool from cmd or powershell. In any case it is a java program and you need to install java first.
