### ISSUE TITLE
Inline math treatment depends on spaces and other chars

### ISSUE THREAD

**Issue by dcervenkov** [sylvainhalle/textidote#55]
When processing the following file

```latex
\documentclass{article}
\begin{document}
An example showing problems with inline math like $\theta_b$ and 
$\theta_b\geq3$ but not $\theta_b \geq 3$ or $\theta_b=3$.
\end{document}
```

I get these errors
```
* L5C58-L5C67 Possible spelling mistake found. Suggestions: [theta, thetas] 
  (57) [lt:en:MORFOLOGIK_RULE_EN_US] 
  th inline math like $\theta_b$ and $\theta_b\geq3$
                       ^^^^^^^^^^
* L5C73-L5C80 Possible spelling mistake found. Suggestions: [theta, thetas] 
  (70) [lt:en:MORFOLOGIK_RULE_EN_US] 
   like $\theta_b$ and $\theta_b\geq3$ but not $\the
                        ^^^^^^^^
```

Seems some inline math is not cleaned properly.

**Comment by sylvainhalle** [comment]
This is caused by the regex that detects inline math, which is currently this:
> ^\\$.*?[^\\\\]\\$

It does not detect inline math that contains backslashes. However, if I remove `[^\\\\]` from the regex, this time it will fail to clean inline math that contains `\$`, so I am a bit at a loss here.

This is a mild example of #56: I added a rule to interpret simple inline math, and now it looks like I am starting to have to interpret more and more of it...

**Comment by matze-dd** [comment]
Hi Silvain,

in a smaller related project, I use the Python-style regex
r'\$([^\\$]|\\.)*\$'.
Something like that should work here, too.

Matthias

**Comment by matze-dd** [comment]
Sorry, there was again a mistake (even with preview)
r'\\$([^\\\\$]|\\\\.)*\\$'
Inside of the math, there should be no \\, no $, or the \\ should eat the next character.

**Comment by PinkieSwirl** [comment]
@sylvainhalle Maybe you could implement a solution that reads in regular expression (one per line) and just give this one as an example and say its not perfect. This way if someone wants to change/add/whatever do with it its possible without additional work for you.

**Comment by sylvainhalle** [comment]
@PinkieSwirl That's an interesting suggestion, but I think for the moment, I'll go with @matze-dd's regex and see if I get more compaints in the next release. ;-)

**Comment by sylvainhalle** [comment]
This was a tricky one. I couldn't get the regex suggested by @matze-dd working in Java. So I used a more brutal approach, and replaced the regex trick by a full-fledged method. Seems to do what we want based on the unit tests I wrote!
