### ISSUE TITLE
Nullpointer exception when checking grammer with LanguageTool

### ISSUE THREAD

**Issue by JorricksTU** [sylvainhalle/textidote#6]
Hello,

I've been trying to get this to work. However, the following error occurs when I set the English grammar check on. This happened for two computers running the latest version and the version before that.
![image](https://user-images.githubusercontent.com/20257392/41810162-ea4a5336-76f9-11e8-8727-a2663faec28d.png)

Could you maybe check it out?

PS. Amazing that you are doing this project! Thumbs up

**Comment by sylvainhalle** [comment]
Hi! Thanks for your good comments about TeXtidote. Do you have a minimal example I could run so I can check why this error occurs?

**Comment by sylvainhalle** [comment]
Hello Jorricks,

Thanks for your input. The new release (0.3) should fix the problem you have.

**Comment by JorricksTU** [comment]
Amazing! I love how the HTML pages work!
