### ISSUE TITLE
[Feature request] output error locations and messages in parsable format (such as JSON, XML, etc.)

### ISSUE THREAD

**Issue by sim590** [sylvainhalle/textidote#60]
It would be very nice if this plugin could output information in such a manner. This could enable writing some plugins for text editors to point out errors in the file directly.

An already existing and relevant plugin that comes to mind is [`vimtex`][vimtex]. A new feature highlighting errors and showing them in the *quickfix* (or *location*) window would be a perfect addition to this plugin.

[vimtex]: https://github.com/lervag/vimtex/

**Comment by sim590** [comment]
If that's of any interest to you, I have opened a feature request on Vimtex's repository. As I have pointed out on that page, some vim plugin already interfaces with LanguageTool directly. Therefore, I shall go and check how they do it before saying that #60 is actually relevant. May be it's not needed... Would you know?

**Comment by sylvainhalle** [comment]
That would be nice indeed, and not so hard to implement. Will flag this as a feature for the next release.

**Comment by sim590** [comment]
Thanks for your quick response!

After checking the Vim plugin for LanguageTool, I have found that [it uses LanguageTool's XML output](https://github.com/dpelle/vim-LanguageTool/blob/master/plugin/LanguageTool.vim#L282). If textidote can do the same, then reusing the plugin's code will be even easier.

**Comment by sylvainhalle** [comment]
XML is deprecated, so it should be JSON
