### ISSUE TITLE
German grammer check

### ISSUE THREAD

**Issue by gilbertf** [sylvainhalle/textidote#67]
Checking the spelling of a german (de) latex document raises multiple incorrect results of type "lt:de:DE_CASE" since environments like sections are not recognized as the beginning of a new sentance.

**Comment by sylvainhalle** [comment]
This may be related to #63. In your source file, is there a blank line between the heading and the text? Better yet, could you provide me an input file that shows what you are saying? Thank you!

**Comment by gilbertf** [comment]
I have the following document:

\documentclass[]{scrbook}
\begin{document}
\chapter{Einleitung}
Dies ist ein erster Testsatz. Hier folgt ein zweiter.
\end{document}

The first "Dies" is highlighted in the html output with the following warning: "Außer am Satzanfang werden nur Nomen und Eigennamen großgeschrieben. Suggestions: [dies] (11) [lt:de:DE_CASE]"
