### ISSUE TITLE
Empty output on --clean if file does not begin with \begin{document}

### ISSUE THREAD

**Issue by nasosev** [sylvainhalle/textidote#74]
Empty output on --clean if file does not begin with \begin{document}.

When running on individual chapters for example, there is no \begin{document} in the tex file.

Workaround is to simple add this manually to the .tex file.

**Comment by sylvainhalle** [comment]
I don't think this is a bug; for files that do not contain a `\begin{document}`, you should use the `--read-all` command line option.
