### ISSUE TITLE
TeXtidote not actually checking language

### ISSUE THREAD

**Issue by JorricksTU** [sylvainhalle/textidote#76]
Hello,

The TeXtidote application does check my file for the predefined mentioned warning (in the readme), but there is nothing that illustrates it actually doing extra work with --check en. There are several typos that I added but nothing is changing. Any ideas what could be going on? Is it not able to access the languageTool?

My command is:
java -jar textidote.jar --check en --html "./thesis.tex" > "report4.html"

I'm running it on a Mac OS 10.14.4.

**Comment by sylvainhalle** [comment]
Hi! Could you try with the `--read-all` option and tell me if it changes something?

**Comment by JorricksTU** [comment]
Yup, I found that out yesterday as well.
Rookie mistake :p 
Thanks for the reply!
