### ISSUE TITLE
Math environnement with \(\)

### ISSUE THREAD

**Issue by PierreMarchand20** [sylvainhalle/textidote#77]
It looks like \\(\\) environnements break everything. It does not recognise simple math command: 
<img width="379" alt="image" src="https://user-images.githubusercontent.com/15056323/55901970-c6e61680-5bca-11e9-939f-c58e6af89e5e.png">

and I think that because of this error, I get other spurious error like 
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/15056323/55902086-0280e080-5bcb-11e9-944c-24cc22e87c10.png">

Note that \\(\\) is preferred to $$ according to chktex for example.

**Comment by sylvainhalle** [comment]
Dupicate of #73
